import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Auth from "./auth/page";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <div>
            <nav className="absoulte flex h-[60px] w-full items-center justify-between bg-blue-100 px-6 py-2">
              <h1>CHATBAWT</h1>
              <Auth />
            </nav>
          </div>
          <div>{children}</div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
